-- CodePulse reference destination schema, PostgreSQL 17+.
-- Specification only: not a claim that an application or database is deployed.
-- Introduce in staged Flyway migrations during Phase 5.
-- UUIDs are generated by Java. All instants are UTC. Do not use ddl-auto=update.
-- MVP: one repository per project, one worker/replica, immutable terminal results.

CREATE TABLE app_user (
    id uuid PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    display_name varchar(80) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(16) NOT NULL DEFAULT 'USER'
        CHECK (role IN ('USER', 'ADMIN')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (email = lower(email) AND email = btrim(email)),
    CHECK (length(display_name) BETWEEN 1 AND 80)
);

CREATE TABLE project (
    id uuid PRIMARY KEY,
    owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    name varchar(80) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    CHECK (name = btrim(name) AND length(name) BETWEEN 1 AND 80),
    UNIQUE (owner_id, name)
);
CREATE INDEX project_owner_created_idx ON project(owner_id, created_at DESC, id);

CREATE TABLE repository_connection (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL UNIQUE REFERENCES project(id) ON DELETE CASCADE,
    github_id bigint NOT NULL CHECK (github_id > 0),
    github_owner varchar(39) NOT NULL,
    github_name varchar(100) NOT NULL,
    canonical_url varchar(500) NOT NULL,
    default_branch varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    verified_at timestamptz NOT NULL,
    CHECK (github_owner ~ '^[A-Za-z0-9][A-Za-z0-9-]{0,38}$'),
    CHECK (github_name ~ '^[A-Za-z0-9._-]{1,100}$'),
    CHECK (github_name NOT IN ('.', '..'))
);
-- The same public GitHub repository can be connected by different owners/projects.
-- Service validates canonical URL/redirect identity; SQL regex is not URL security.

CREATE TABLE analysis_run (
    id uuid PRIMARY KEY,
    repository_id uuid NOT NULL REFERENCES repository_connection(id) ON DELETE CASCADE,
    requested_by uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    status varchar(16) NOT NULL CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    stage varchar(24) NOT NULL CHECK (stage IN (
        'QUEUED', 'RESOLVING', 'DOWNLOADING', 'INVENTORY', 'PARSING',
        'LINKING', 'SCORING', 'PERSISTING', 'COMPLETE', 'FAILED'
    )),
    commit_sha varchar(64),
    source_url varchar(800),
    engine_version varchar(64) NOT NULL,
    parser_version varchar(64) NOT NULL,
    metric_version varchar(64) NOT NULL,
    graph_version varchar(64) NOT NULL,
    risk_policy_version varchar(64) NOT NULL,
    effective_config jsonb NOT NULL,
    config_hash char(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    worker_boot_id uuid,
    total_files integer CHECK (total_files >= 0),
    java_files integer CHECK (java_files >= 0),
    eligible_files integer CHECK (eligible_files >= 0),
    parsed_files integer CHECK (parsed_files >= 0),
    parse_failed_files integer CHECK (parse_failed_files >= 0),
    excluded_java_files integer CHECK (excluded_java_files >= 0),
    completed_files integer NOT NULL DEFAULT 0 CHECK (completed_files >= 0),
    summary jsonb,
    warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
    error_code varchar(64),
    error_message varchar(500),
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    CHECK (commit_sha IS NULL OR commit_sha ~ '^[0-9a-f]{40,64}$'),
    CHECK (config_hash ~ '^[0-9a-f]{64}$'),
    CHECK (jsonb_typeof(effective_config) = 'object'),
    CHECK (jsonb_typeof(warnings) = 'array'),
    CHECK (summary IS NULL OR jsonb_typeof(summary) = 'object'),
    CHECK (started_at IS NULL OR started_at >= created_at),
    CHECK (finished_at IS NULL OR finished_at >= created_at),
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    CHECK (eligible_files IS NULL OR completed_files <= eligible_files),
    CHECK (
        (status = 'QUEUED' AND stage = 'QUEUED' AND started_at IS NULL AND finished_at IS NULL)
        OR (status = 'RUNNING' AND stage IN ('RESOLVING', 'DOWNLOADING', 'INVENTORY',
            'PARSING', 'LINKING', 'SCORING', 'PERSISTING')
            AND started_at IS NOT NULL AND worker_boot_id IS NOT NULL AND finished_at IS NULL)
        OR (status = 'SUCCEEDED' AND stage = 'COMPLETE' AND started_at IS NOT NULL
            AND finished_at IS NOT NULL AND commit_sha IS NOT NULL
            AND source_url IS NOT NULL AND summary IS NOT NULL)
        OR (status = 'FAILED' AND stage = 'FAILED' AND finished_at IS NOT NULL
            AND error_code IS NOT NULL)
    ),
    CHECK (status = 'FAILED' OR (error_code IS NULL AND error_message IS NULL)),
    CHECK (status <> 'SUCCEEDED' OR (
        total_files IS NOT NULL AND java_files IS NOT NULL AND eligible_files IS NOT NULL
        AND parsed_files IS NOT NULL AND parsed_files > 0
        AND parse_failed_files IS NOT NULL AND excluded_java_files IS NOT NULL
        AND java_files = eligible_files + excluded_java_files
        AND eligible_files = parsed_files + parse_failed_files
        AND completed_files = eligible_files AND total_files >= java_files
    ))
);
CREATE UNIQUE INDEX analysis_one_active_per_repository_idx
    ON analysis_run(repository_id) WHERE status IN ('QUEUED', 'RUNNING');
CREATE INDEX analysis_repository_history_idx ON analysis_run(repository_id, created_at DESC, id);
CREATE INDEX analysis_queue_idx ON analysis_run(created_at, id) WHERE status = 'QUEUED';
CREATE INDEX analysis_requester_time_idx ON analysis_run(requested_by, created_at DESC);

CREATE TABLE file_snapshot (
    id uuid PRIMARY KEY,
    analysis_id uuid NOT NULL REFERENCES analysis_run(id) ON DELETE CASCADE,
    relative_path varchar(512) NOT NULL,
    content_sha256 char(64),
    package_name varchar(512),
    source_scope varchar(16) NOT NULL CHECK (source_scope IN ('MAIN', 'TEST', 'OTHER_SOURCE')),
    eligible boolean NOT NULL,
    parse_status varchar(16) NOT NULL CHECK (parse_status IN ('PARSED', 'PARSE_FAILED', 'SKIPPED')),
    disposition_code varchar(64),
    byte_size bigint NOT NULL CHECK (byte_size >= 0),
    physical_loc integer CHECK (physical_loc >= 0),
    ncloc integer CHECK (ncloc >= 0),
    comment_lines integer CHECK (comment_lines >= 0),
    blank_lines integer CHECK (blank_lines >= 0),
    class_count integer CHECK (class_count >= 0),
    interface_count integer CHECK (interface_count >= 0),
    enum_count integer CHECK (enum_count >= 0),
    record_count integer CHECK (record_count >= 0),
    annotation_count integer CHECK (annotation_count >= 0),
    anonymous_class_count integer CHECK (anonymous_class_count >= 0),
    method_count integer CHECK (method_count >= 0),
    constructor_count integer CHECK (constructor_count >= 0),
    executable_count integer CHECK (executable_count >= 0),
    lambda_count integer CHECK (lambda_count >= 0),
    todo_count integer CHECK (todo_count >= 0),
    fixme_count integer CHECK (fixme_count >= 0),
    max_method_complexity integer CHECK (max_method_complexity >= 0),
    max_method_ncloc integer CHECK (max_method_ncloc >= 0),
    observed_fan_in integer CHECK (observed_fan_in >= 0),
    observed_fan_out integer CHECK (observed_fan_out >= 0),
    import_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    attention_score smallint CHECK (attention_score BETWEEN 0 AND 100),
    priority varchar(16) NOT NULL CHECK (priority IN ('UNASSESSED', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH')),
    UNIQUE (analysis_id, relative_path),
    UNIQUE (analysis_id, id),
    CHECK (length(relative_path) > 0),
    CHECK (relative_path !~ '(^/|(^|/)\.\.(/|$))'),
    CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    CHECK (jsonb_typeof(import_evidence) = 'object'),
    CHECK ((parse_status = 'SKIPPED') = (NOT eligible)),
    CHECK (
        (parse_status = 'PARSED' AND content_sha256 IS NOT NULL AND ncloc IS NOT NULL
            AND max_method_complexity IS NOT NULL AND max_method_ncloc IS NOT NULL
            AND observed_fan_in IS NOT NULL AND observed_fan_out IS NOT NULL
            AND attention_score IS NOT NULL AND priority <> 'UNASSESSED')
        OR (parse_status <> 'PARSED' AND attention_score IS NULL AND priority = 'UNASSESSED'
            AND disposition_code IS NOT NULL)
    )
);
CREATE INDEX file_score_idx ON file_snapshot(analysis_id, attention_score DESC, id);
CREATE INDEX file_priority_idx ON file_snapshot(analysis_id, priority, attention_score DESC, id);
CREATE INDEX file_package_idx ON file_snapshot(analysis_id, package_name);
-- Priority ranking is an explicit CASE expression, not alphabetical ordering.

CREATE TABLE method_metric (
    id uuid PRIMARY KEY,
    analysis_id uuid NOT NULL,
    file_id uuid NOT NULL,
    owner_label varchar(512) NOT NULL,
    signature varchar(4096) NOT NULL,
    declaration_kind varchar(24) NOT NULL CHECK (declaration_kind IN ('METHOD', 'CONSTRUCTOR', 'COMPACT_CONSTRUCTOR')),
    has_body boolean NOT NULL,
    begin_line integer NOT NULL CHECK (begin_line >= 1),
    end_line integer NOT NULL,
    ncloc integer NOT NULL CHECK (ncloc >= 0),
    complexity integer,
    FOREIGN KEY (analysis_id, file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
    CHECK (end_line >= begin_line),
    CHECK ((has_body AND complexity >= 1 AND complexity IS NOT NULL)
        OR (NOT has_body AND complexity IS NULL))
);
CREATE INDEX method_file_idx ON method_metric(analysis_id, file_id, begin_line, id);
-- Do not index the full 4096-character signature with a B-tree unique constraint.
-- App result validation rejects duplicate (owner, signature, begin_line) identities.

CREATE TABLE dependency_edge (
    id uuid PRIMARY KEY,
    analysis_id uuid NOT NULL REFERENCES analysis_run(id) ON DELETE CASCADE,
    source_file_id uuid NOT NULL,
    target_file_id uuid NOT NULL,
    kind varchar(32) NOT NULL CHECK (kind = 'EXPLICIT_IMPORT'),
    evidence jsonb NOT NULL,
    FOREIGN KEY (analysis_id, source_file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
    FOREIGN KEY (analysis_id, target_file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
    UNIQUE (analysis_id, source_file_id, target_file_id, kind),
    CHECK (source_file_id <> target_file_id),
    CHECK (jsonb_typeof(evidence) = 'object')
);
CREATE INDEX edge_incoming_idx ON dependency_edge(analysis_id, target_file_id, source_file_id);
-- The unique index already supports outgoing edge queries.

CREATE TABLE finding (
    id uuid PRIMARY KEY,
    analysis_id uuid NOT NULL,
    file_id uuid NOT NULL,
    rule_code varchar(64) NOT NULL,
    severity varchar(16) NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'HIGH')),
    begin_line integer,
    end_line integer,
    message varchar(500) NOT NULL,
    evidence jsonb NOT NULL,
    FOREIGN KEY (analysis_id, file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
    CHECK ((begin_line IS NULL AND end_line IS NULL)
        OR (begin_line IS NOT NULL AND end_line IS NOT NULL AND begin_line >= 1 AND end_line >= begin_line)),
    CHECK (jsonb_typeof(evidence) = 'object')
);
CREATE INDEX finding_file_idx ON finding(analysis_id, file_id, rule_code, id);

CREATE TABLE risk_factor (
    analysis_id uuid NOT NULL,
    file_id uuid NOT NULL,
    factor_code varchar(32) NOT NULL CHECK (factor_code IN (
        'MAX_COMPLEXITY', 'FILE_NCLOC', 'MAX_METHOD_NCLOC', 'OBSERVED_FAN_OUT', 'OBSERVED_FAN_IN'
    )),
    raw_value numeric(14,4) NOT NULL CHECK (raw_value >= 0),
    low_threshold numeric(14,4) NOT NULL,
    high_threshold numeric(14,4) NOT NULL,
    normalized_value numeric(12,10) NOT NULL CHECK (normalized_value BETWEEN 0 AND 1),
    weight numeric(5,2) NOT NULL CHECK (weight BETWEEN 0 AND 100),
    contribution numeric(14,10) NOT NULL CHECK (contribution >= 0),
    PRIMARY KEY (file_id, factor_code),
    FOREIGN KEY (analysis_id, file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
    CHECK (high_threshold > low_threshold),
    CHECK (contribution <= weight)
);
CREATE INDEX factor_analysis_idx ON risk_factor(analysis_id, file_id);

-- Service-level invariants, all covered by integration tests:
-- 1. requested_by equals the project's owner in MVP.
-- 2. Terminal snapshots never change; deletes require no active work.
-- 3. Exactly five factors exist for each parsed/scored file.
-- 4. Parsed metric fields are complete; unsupported data stays NULL, never guessed.
-- 5. Aggregate counts match file rows and scope-aware summary calculations.
-- 6. Every source path passes the stronger platform-independent path validator.
-- 7. Snapshot config is canonicalized before SHA-256; raw JSON serialization order
--    is not assumed stable. Integers/booleans/strings only in MVP metric config.
-- 8. Risk formula is applied in full precision; stored decimals are explanatory
--    approximations. Recompute final rounding from raw values and policy.
-- 9. Repository rename/transfer identity and public visibility are checked at scan time.

-- V1 extension schemas. Do not install until selecting the corresponding feature.
-- For comparison-only V1, no extra tables are required.

-- CREATE TABLE file_activity (
--     analysis_id uuid NOT NULL,
--     file_id uuid PRIMARY KEY,
--     window_start timestamptz NOT NULL,
--     window_end timestamptz NOT NULL,
--     touching_commit_count integer CHECK (touching_commit_count >= 0),
--     changed_lines bigint CHECK (changed_lines >= 0),
--     last_changed_at timestamptz,
--     coverage varchar(24) NOT NULL CHECK (coverage IN ('COMPLETE', 'PARTIAL', 'UNAVAILABLE')),
--     reason_code varchar(64),
--     history_policy_version varchar(64) NOT NULL,
--     FOREIGN KEY (analysis_id, file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
--     CHECK (window_end >= window_start)
-- );

-- CREATE TABLE clone_group (
--     id uuid PRIMARY KEY,
--     analysis_id uuid NOT NULL REFERENCES analysis_run(id) ON DELETE CASCADE,
--     algorithm_version varchar(64) NOT NULL,
--     token_hash char(64) NOT NULL,
--     token_count integer NOT NULL CHECK (token_count >= 50),
--     UNIQUE (analysis_id, id)
-- );
-- CREATE TABLE clone_occurrence (
--     id uuid PRIMARY KEY,
--     analysis_id uuid NOT NULL,
--     group_id uuid NOT NULL,
--     file_id uuid NOT NULL,
--     begin_line integer NOT NULL CHECK (begin_line >= 1),
--     end_line integer NOT NULL,
--     FOREIGN KEY (analysis_id, group_id) REFERENCES clone_group(analysis_id, id) ON DELETE CASCADE,
--     FOREIGN KEY (analysis_id, file_id) REFERENCES file_snapshot(analysis_id, id) ON DELETE CASCADE,
--     CHECK (end_line >= begin_line),
--     UNIQUE (group_id, file_id, begin_line, end_line)
-- );
